shaping_units:
  - name: event
    base_reward: 1.0
    decay_trigger: 10
    decay_rate: 0.5
    recovery_trigger: 50
    recovery_multiplier: 2.0
  - name: heal
    base_reward: 0.5
    decay_trigger: 5
    decay_rate: 0.5
    recovery_trigger: 20
    recovery_multiplier: 2.0
  - name: badge
    base_reward: 5.0
  - name: explore
    base_reward: 0.1
    decay_trigger: 100
    decay_rate: 0.5
    recovery_trigger: 200
    recovery_multiplier: 2.0
  - name: stuck
    base_reward: -0.05
